### ISSUE TITLE
tock-registers dependency fails to compile

### ISSUE THREAD

**Issue by dcompoze** [rust-embedded/register-rs#10]
It seems that that crates.io version of `tock-registers` is out of date, it gives a compilation error:

```
error[E0557]: feature has been removed
 --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tock-registers-0.6.0/src/lib.rs:5:12
  |
  | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates
```

This feature has been renamed to `#![feature(const_fn_trait_bound)]` in the tock repository.

**Comment by andre-richter** [comment]
Yes, for now you’ll have to pin the compiler version. You can check the rust-toolchain file in the tock repository for reference.

**Comment by dcompoze** [comment]
Great, that should work.
