### ISSUE TITLE
Using register-rs for AHCI controllers?

### ISSUE THREAD

**Issue by ethindp** [rust-embedded/register-rs#4]
Hi there,
I have a set of structures for the Advanced Host Controller Interface (AHCI) specification to communicate with SATA devices. They can be found [here](https://github.com/ethindp/kernel/blob/master/src/drivers/storage/ahci/internal.rs). Currently, the driver fails to function, giving alignment errors. I would like to adapt that driver to use register-rs, but I am not sure how. Some of the structures are easily adaptable, but others, like the PRDT, have arrays of PrDT entries, and I'm unsure what to do about those. Is it possible to adapt those structures to use register-rs at this time?

**Comment by andre-richter** [comment]
Are you are talking about the `register_structs!` macro specifically?

You can do arrays. Taking the example [from here](https://github.com/tock/tock/tree/master/libraries/tock-register-interface):

```rust
register_structs! {
    Registers {
        ...
        (0x00C => array: [ReadWrite<u32>; 4])
```

**Comment by ethindp** [comment]
That's sort of what I'm talking about. The arrays I need can range from 1 to 32, for one, and 1 to 65535, for the other. Its a problem I've been generally trying to solve since I started writing the driver. In C you can declare an array and read/write outside its range, but in rust that's not possible, at least from what I know. I've been trying to (safely if at all best) circumvent that issue for a while now, because Idon't want to create an array of 65535 structures -- that not only lengthens compilation times but makes the binary much larger. The code I'm trying to "port" (because I've never done an AHCI driver before) is available at https://wiki.osdev.org/AHCI and my "ported" code is available at https://github.com/ethindp/kernel/blob/master/src/drivers/storage/ahci.rs and https://github.com/ethindp/kernel/blob/master/src/drivers/storage/ahci/internal.rs. The driver itself is currently disabled because it doesn't work (unfortunately) despite me hacking on it for weeks. :P
I was hoping that this library might make things easier,but its hard to map what I have right now to what this library expects.

**Comment by andre-richter** [comment]
> That's sort of what I'm talking about. The arrays I need can range from 1 to 32, for one, and 1 to 65535, for the other. Its a problem I've been generally trying to solve since I started writing the driver.

Unfortunately, the library won't help you there. It has no magic sauce for that specific problem.
The provided macro in the end evaluates into standard Rust code, so what you can't solve with Rust natively this library also can't.

I didn't have time to dig into your problem, but dealing with arrays that change size dynamically sounds like you either need some sort of heap allocator or indeed need to pre-allocate for the maximum array size.

**Comment by andre-richter** [comment]
Closing for now.
