### ISSUE TITLE
Padding of the first register_struct element feels buggy

### ISSUE THREAD

**Issue by Trolldemorted** [rust-embedded/register-rs#5]
Let's take this struct definition:

```
register_structs! {
    pub LegacyVirtioDeviceRegister {
        //(0x000 => magic_value: ReadOnly<u32>),
        (0x004 => version: ReadOnly<u32>),
        (0x008 => device_id: ReadOnly<u32>),
[...]
```

If I do not comment out the magic value, I get the expected values (magic_value=0x‭74726976‬, version=1). If I do comment it out, the version becomes 0x‭74726976‬, which is why I believe there might be no padding before the first element.

**Comment by Trolldemorted** [comment]
After consulting tock's docs I realized you **must not** have gaps in your struct definition.

Since we unambiguously state the address and width of that field I assume this could be handled better? Right now it is kind of a footgun.

**Comment by andre-richter** [comment]
I know that part is tricky. Since we inherit it from tock it's best addressed there, though.

But we should mention this prominently in the readme here to address this issue for now.
