### ISSUE TITLE
Question about register offsets

### ISSUE THREAD

**Issue by ethindp** [rust-embedded/register-rs#7]
I'm writing an AHCI driver, and I'm trying to encode the bits from the AHCI specification. I'm using this crate to define the CAP register (offset `00h`). These bits are found in section 3.1.1 (Offset `00h`: CAP – HBA Capabilities) of the [AHCI specification](https://www.intel.com/content/www/us/en/io/serial-ata/serial-ata-ahci-spec-rev1-3-1.html).

My code is:

```rust
register_bitfields! {
u32,
CAP [
S64A OFFSET(31) NUMBITS(1) [],
SNCQ OFFSET(30) NUMBITS(1) [],
SSNTF OFFSET(29) NUMBITS(1) [],
SMPS OFFSET(28) NUMBITS(1) [],
SSS OFFSET(27) NUMBITS(1) [],
SALP OFFSET(26) NUMBITS(1) [],
SAL OFFSET(25) NUMBITS(1) [],
SCLO OFFSET(24) NUMBITS(1) [],
ISS OFFSET(23) NUMBITS(4) [
Gen1 = 0b0001,
Gen2 = 0b0010,
Gen3 = 0b0011
],
SAM OFFSET(18) NUMBITS(1) [],
SPM OFFSET(17) NUMBITS(1) [],
FBSS OFFSET(16) NUMBITS(1) [],
PMD OFFSET(15) NUMBITS(1) [],
SSC OFFSET(14) NUMBITS(1) [],
PSC OFFSET(13) NUMBITS(1) [],
NCS OFFSET(12) NUMBITS(5) [],
CCCS OFFSET(7) NUMBITS(1) [],
EMS OFFSET(6) NUMBITS(1) [],
SXS OFFSET(5) NUMBITS(1) [],
NP OFFSET(4) NUMBITS(5) []
]
}
```

The question I have is this: are the offsets correct, and is "shift" the number of bits to shift left by (e.g.: `1<<31` for bit 31)? The documentation of the Tock registers crate didn't specify precisely what that was.

**Comment by andre-richter** [comment]
Look correct to me on first sight.

**Comment by andre-richter** [comment]
Closing for now. I can reopen if there are follow-up questions :+1:
