### ISSUE TITLE
Cargo.toml manifest fails to parse

### ISSUE THREAD

**Issue by dcompoze** [rust-embedded/register-rs#9]
Hello,
Is this library in usable state?
I downloaded the source code and ran `cargo check`, the output was:

```
error: failed to parse manifest at `/home/admin/Storage/Code/repositories/rust/register-rs/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.6.x` for dependency `tock-registers`

Caused by:
  unexpected character 'x' while parsing patch version number
```

Why does the version number contain the letter `x`?

**Comment by dcompoze** [comment]
Seems to have gone away after updating cargo, does this work the same as the glob `*` pattern?

**Comment by andre-richter** [comment]
Yes, it’s a glob.

**Comment by dcompoze** [comment]
Thanks, found the relevant code here: https://docs.rs/semver/1.0.3/src/semver/parse.rs.html#184-194
